### ISSUE TITLE
When second video auto-plays, it plays behind the UI

### ISSUE THREAD

**Issue by brianboyer** [nprapps/roku-tinydesk#161]
I'm playing things for the first time, my watched list is empty. (It shouldn't be, I've used the app many times before, but #160 is happening.) I watched a video, it ended, the next video began to auto-play, but it looks like the video is *behind* the UI.

**Comment by onyxfish** [comment]
Replicated w/ my existing history. Must have created this bug in the last release. Damn it.

**Comment by onyxfish** [comment]
Nope, I was wrong. Only happens on a clean install. What I see:

video
interstitial
flash of grid
loading
grid, with audio playing behind

Something to do with creating the watched list?

**Comment by onyxfish** [comment]
Two guesses:

* Something to do with creating/showing the watched list
* Something to do with the ad code

**Comment by onyxfish** [comment]
Disabling ads completely did not fix this (PLAY_ADS = false)

**Comment by onyxfish** [comment]
Flicker not visible after second interstitial so pretty sure this has something to do with updating the grid.
