### ISSUE TITLE
Unwatched category is mismatched

### ISSUE THREAD

**Issue by brianboyer** [nprapps/roku-tinydesk#162]
From a user: "When I scroll through the "unwatched" category, each video I click on has mismatched video." "I have a Roku 3100X, software version 5.5, build 320"

**Comment by onyxfish** [comment]
I have also seen this.

**Comment by onyxfish** [comment]
I have absolutely no idea how to replicate this. Things I've tried:

* Adding videos from different rows
* Playing videos from watched list in different orders
* Playing from the search list
* Playing from other lists after playing watched list then returning

I'm inclined to believe this may be a firmware issue as this sort of mismatch shouldn't even be possible. Each row item is associated with a ContentItem that contains both its image and "link". There isn't anyway for those things to be set separately.
